In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df_events=pd.read_csv('events.csv')
df_events

,id,user_id,city,state,browser,traffic_source,event_type,creation_date,order_time
0,193079,14759,São Paulo,São Paulo,Chrome,Adwords,cart,2022-10-07,08:35:50
1,157237,12062,São Paulo,São Paulo,Chrome,Adwords,cart,2025-08-13,15:35:03
2,1290688,99790,São Paulo,São Paulo,Safari,Adwords,cart,2023-10-04,18:17:26
3,234294,17942,São Paulo,São Paulo,Chrome,Adwords,cart,2024-04-30,06:15:27
4,1145403,88606,São Paulo,São Paulo,Firefox,Adwords,cart,2025-06-06,12:25:07
...,...,...,...,...,...,...,...,...,...
1293921,610734,46935,London,England,Chrome,YouTube,purchase,2022-08-13,22:52:13
1293922,1233354,95411,Sunderland,England,IE,YouTube,purchase,2025-08-18,09:19:26
1293923,1229153,95090,London,England,Chrome,YouTube,purchase,2026-01-13,23:22:44
1293924,552834,42491,Middlesbrough,England,Firefox,YouTube,purchase,2022-07-30,13:36:01
1293925,410614,31417,Ashton-in-Makerfield,England,Chrome,YouTube,purchase,2025-11-01,22:31:58

In [6]:
df_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1293926 entries, 0 to 1293925
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   id              1293926 non-null  int64
 1   user_id         1293926 non-null  int64
 2   city            1281000 non-null  object
 3   state           1293926 non-null  object
 4   browser         1293926 non-null  object
 5   traffic_source  1293926 non-null  object
 6   event_type      1293926 non-null  object
 7   creation_date   1293926 non-null  object
 8   order_time      1293926 non-null  object
dtypes: int64(2), object(7)
memory usage: 88.8+ MB

In [8]:
df_events.shape

(1293926, 9)

In [9]:
df_events['creation_date'] = pd.to_datetime(df_events['creation_date'])

In [10]:
df_events['city'].unique()

array(['São Paulo', 'Embu-Guaçu', 'Cajamar', ..., 'Orthez',
       'Gibson Desert North', 'High stone market'],
      shape=(7532,), dtype=object)

In [11]:
df_events['state'].unique()

array(['São Paulo', 'Brussels', 'Beijing', 'New York', 'Extremadura',
       'Inner Mongolia Autonomous Region', 'Berlin', 'Tokyo', 'Liaoning',
       'Sachsen', 'Seoul', 'Comunidad Valenciana', 'Jilin',
       "Provence-Alpes-Côte d'Azur", 'Castilla-La Mancha', 'Andalucía',
       'Brandenburg', 'Heilongjiang', 'Galicia', 'Pennsylvania',
       'Flanders', 'Cataluña', 'Massachusetts', 'Delaware', 'Shanghai',
       'New South Wales', 'País Vasco', 'Virginia', 'Maryland',
       'Rio de Janeiro', 'Jiangsu', 'Hamburg', 'Niedersachsen',
       'Kanagawa', 'Bourgogne-Franche-Comté', 'Aragón', 'Anhui',
       'Castilla y León', 'Shandong', 'Schleswig-Holstein', 'La Rioja',
       'Chiba', 'Auvergne-Rhône-Alpes', 'Normandie', 'North Carolina',
       'Bremen', 'Comunidad de Madrid', 'Centre-Val de Loire',
       'Rhode Island', 'Bretagne', 'Espírito Santo', 'South Carolina',
       'Shanxi', 'Georgia', 'Tianjin', 'Victoria', 'Daejeon', 'Occitanie',
       'Ibaraki', 'Zhejiang', 'Hokkaido', 'Wallonia',
       'Mecklenburg-Vorpommern', 'Nouvelle-Aquitaine', 'Gangwon-do',
       'District of Columbia', 'Región de Murcia', 'New Hampshire',
       'Navarra', 'Iwate', 'Grand Est', 'Corse', 'Minas Gerais',
       'Remote territory', 'Hauts-de-France', 'West Virginia',
       'Australian Capital Territory', 'Aomori', 'Sachsen-Anhalt',
       'Florida', 'Jiangxi', 'Chungcheongnam-do', 'Saitama',
       'Nordrhein-Westfalen', 'Fujian', 'Canarias', 'Alabama',
       'Chung-cheong bukdo', 'Tennessee', 'Gunma', 'Mississippi',
       'Queensland', 'Chongqing', 'Incheon Metropolitan City', 'Kentucky',
       'Bahia', 'Gyeonggi-do', 'Hunan', 'Shizuoka', 'Hubei', 'Ohio',
       'Pays de la Loire', 'Henan', 'Indiana', 'Aichi', 'Michigan',
       'Sergipe', 'Iowa', 'Hebei', 'South Australia', 'Gwangju',
       'Guangdong', 'Pernambuco', 'Jeollanam-do',
       'Guangxi Zhuang Autonomous Region', 'Wisconsin', 'Rheinland-Pfalz',
       'Osaka', 'Guizhou', 'Minnesota', 'Principado de Asturias',
       'Hessen', 'Maine', 'Ceuta', 'Melilla', 'Jeollabuk do', 'Hainan',
       'Alagoas', 'South Dakota', 'Paraíba', 'North Dakota',
       'Dolnośląskie', 'Rio Grande do Norte', 'Montana', 'Illinois',
       'Ceará', 'Connecticut', 'Busan', 'Western Australia', 'Sichuan',
       'Kyoto', 'Gyeongsangnam-do', 'Missouri', 'Piauí', 'Yunnan',
       'Maranhão', 'Lubuskie', 'Hyogo', 'Kansas', 'Pará',
       'Ulsan Metropolitan City', 'Amazonas', 'Nebraska', 'Acre',
       'New Jersey', 'Louisiana', 'Islas Baleares',
       'Daegu Metropolitan City', 'Distrito Federal', 'Shaanxi',
       'Baden-Württemberg', 'Gyeongsangbuk-do', 'Arkansas', 'Hiroshima',
       'Goiás', 'Gansu province', 'Oklahoma',
       'Ningxia Hui Autonomous Region', 'Île-de-France', 'Texas',
       'Rondônia', 'Tocantins', 'Mato Grosso', 'Mato Grosso do Sul',
       'Colorado', 'Qinghai', 'Paraná', 'Fukuoka', 'Bayern',
       'Xinjiang Uygur Autonomous Region', 'Utah', 'Arizona', 'Nagasaki',
       'New Mexico', 'Santa Catarina', 'Nevada', 'Okinawa', 'California',
       'Rio Grande do Sul', 'Hawaii', 'Oregon', 'Cantabria', 'Saarland',
       'Amapá', 'Tasmania', 'Zachodniopomorskie', 'Wyoming', 'Idaho',
       'Oita', 'Mie', 'Thüringen', 'Vorarlberg', 'Yamaguchi',
       'Washington', 'Alaska', 'Scotland', 'England', 'Northern Ireland',
       'Wales', 'Bagmati region', 'Miyagi', 'Wakayama', 'Okayama',
       'Northern Territory', 'Roraima', 'Kochi', 'Miyazaki', 'Gifu',
       'Jeju Special Self-Governing Province', 'Kagoshima', 'Fukushima',
       'Shimane', 'Kagawa', 'Nagano', 'Tochigi', 'Nara', 'Kumamoto',
       'Shiga'], dtype=object)

In [12]:
missing = df_events.isnull().sum()
missing_pct = (missing / len(df_events) * 100).round(2)

missing_df = pd.DataFrame({
    'Valori Nulli': missing,
    'Percentuale (%)': missing_pct
})

print("Valori mancanti per colonna:")
print(missing_df[missing_df['Valori Nulli'] > 0].sort_values('Valori Nulli', ascending=False))

Valori mancanti per colonna:
      Valori Nulli  Percentuale (%)
city         12926              1.0

In [13]:
df_events[df_events['city'].isna()]

,id,user_id,city,state,browser,traffic_source,event_type,creation_date,order_time
270,844564,65084,NaN,Galicia,Firefox,Adwords,cart,2026-01-11,22:13:51
496,533538,40987,NaN,Virginia,Chrome,Adwords,cart,2024-11-01,22:33:19
685,802472,61942,NaN,Comunidad de Madrid,Chrome,Adwords,cart,2023-11-25,10:41:50
698,913670,70534,NaN,Andalucía,Safari,Adwords,cart,2026-02-10,12:51:35
699,1119906,86643,NaN,Espírito Santo,IE,Adwords,cart,2023-08-07,16:35:31
...,...,...,...,...,...,...,...,...,...
1293787,1095535,84706,NaN,Pará,Firefox,YouTube,purchase,2024-08-23,21:53:32
1293789,170347,13052,NaN,Pará,Safari,YouTube,purchase,2023-02-12,05:10:17
1293790,520839,39949,NaN,Pará,Chrome,YouTube,purchase,2026-02-10,17:04:11
1293792,124313,9554,NaN,Pará,Chrome,YouTube,purchase,2025-01-25,23:22:30
1293795,637983,49150,NaN,Amapá,IE,YouTube,purchase,2025-07-12,18:21:25

In [14]:
df_events[df_events['user_id'].isna()]

Empty DataFrame
Columns: [id, user_id, city, state, browser, traffic_source, event_type, creation_date, order_time]
Index: []

In [3]:
df_1=pd.read_csv('df_events.csv')
df_1

,id,user_id,city,state,browser,traffic_source,event_type,creation_date,order_time
0,137338,10589,Sapporo,Hokkaido,Chrome,Adwords,cart,2023-01-11,18:25:29
1,445862,33856,Oshu-shi,Iwate,Other,Adwords,cart,2022-11-22,00:44:21
2,1298049,99501,São Paulo,São Paulo,Chrome,Adwords,cart,2025-09-17,08:40:02
3,1239991,95100,São Paulo,São Paulo,Chrome,Adwords,cart,2024-06-27,08:47:33
4,772152,58975,São Paulo,São Paulo,Other,Adwords,cart,2025-09-13,06:00:21
...,...,...,...,...,...,...,...,...,...
1304366,695368,53139,Portsmouth,England,Firefox,YouTube,purchase,2024-12-07,12:31:54
1304367,471487,35871,Eastleigh,England,Chrome,YouTube,purchase,2025-01-01,09:35:58
1304368,14240,1054,St Helens,England,Other,YouTube,purchase,2020-02-17,14:36:32
1304369,613940,46943,Warrington,England,Chrome,YouTube,purchase,2025-10-18,00:17:20
1304370,584336,44698,Watford,England,Chrome,YouTube,purchase,2024-09-04,02:52:24

In [6]:
df_1[df_1['id']=='1759151']

Empty DataFrame
Columns: [id, user_id, city, state, browser, traffic_source, event_type, creation_date, order_time]
Index: []

In [9]:
df_2=pd.read_csv('prova.csv')
df_2

,id,user_id,city,state,browser,traffic_source,event_type,creation_date,order_time
0,1843936,NaN,São Paulo,São Paulo,Safari,Adwords,cancel,2020-03-03,01:59:00
1,1366432,NaN,São Paulo,São Paulo,Chrome,Adwords,cancel,2023-09-17,02:05:00
2,1791971,NaN,Rio Grande da Serra,São Paulo,Chrome,Adwords,cancel,2019-10-24,01:45:00
3,1416261,NaN,Changzhi,Beijing,Firefox,Adwords,cancel,2025-04-16,15:56:00
4,1539705,NaN,Chizhou,Beijing,Chrome,Adwords,cancel,2021-03-17,19:29:00
...,...,...,...,...,...,...,...,...,...
2428186,94213,7281.0,London,England,Firefox,YouTube,purchase,2025-03-26,19:56:18
2428187,33200,2555.0,Farnborough,England,Firefox,YouTube,purchase,2024-04-21,06:17:17
2428188,116772,9011.0,West Bridgford,England,IE,YouTube,purchase,2026-01-02,11:11:07
2428189,459408,34950.0,Donington,England,Firefox,YouTube,purchase,2025-10-29,01:03:47
2428190,430710,32743.0,Pontarddulais,Wales,Safari,YouTube,purchase,2025-06-24,10:08:59

In [4]:
df_1[df_1['user_id'].isna()]

Empty DataFrame
Columns: [id, user_id, city, state, browser, traffic_source, event_type, creation_date, order_time]
Index: []